TERM_PROGRAM=vscode
TERM=xterm-256color
HOMEBREW_TEMP=/tmp/sdiouane/Homebrew/Temp
SHELL=/bin/zsh
TMPDIR=/var/folders/zz/zyxvpxvq6csfxvn_n000cmm4003551/T/
TERM_PROGRAM_VERSION=1.83.1
ZDOTDIR=/Users/sdiouane
ORIGINAL_XDG_CURRENT_DESKTOP=undefined
MallocNanoZone=0
ZSH=/Users/sdiouane/.oh-my-zsh
USER=sdiouane
LS_COLORS=di=1;36:ln=35:so=32:pi=33:ex=31:bd=34;46:cd=34;43:su=30;41:sg=30;46:tw=30;42:ow=30;43
COMMAND_MODE=unix2003
SSH_AUTH_SOCK=/private/tmp/com.apple.launchd.QBveBbUwxh/Listeners
__CF_USER_TEXT_ENCODING=0x194A1:0x0:0x0
PAGER=less
HOMEBREW_CACHE=/tmp/sdiouane/Homebrew/Caches
LSCOLORS=Gxfxcxdxbxegedabagacad
PATH=/Users/sdiouane/.brew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/munki:/Library/Apple/usr/bin:/Users/sdiouane/.brew/bin
LaunchInstanceID=C7BEE517-72A7-46C0-86DD-272B5499EBB3
USER_ZDOTDIR=/Users/sdiouane
PWD=/Users/sdiouane/Desktop/our_big_shell
LANG=en_US.UTF-8
VSCODE_GIT_ASKPASS_EXTRA_ARGS=--ms-enable-electron-run-as-node
XPC_FLAGS=0x0
XPC_SERVICE_NAME=0
VSCODE_INJECTION=1
SHLVL=2
HOME=/Users/sdiouane
VSCODE_GIT_ASKPASS_MAIN=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass-main.js
LESS=-R
LOGNAME=sdiouane
VSCODE_GIT_IPC_HANDLE=/var/folders/zz/zyxvpxvq6csfxvn_n000cmm4003551/T/vscode-git-9c9844fdba.sock
VSCODE_GIT_ASKPASS_NODE=/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)
GIT_ASKPASS=/Applications/Visual Studio Code.app/Contents/Resources/app/extensions/git/dist/askpass.sh
SECURITYSESSIONID=186a8
COLORTERM=truecolor
_=/usr/bin/env
